### ISSUE TITLE
Update nuget

### ISSUE THREAD

**Issue by kalilistic** [xivapi/NetStone#18]
Hey, would it be possible to push the latest to nuget? My backup plan would be to fork and publish my own nuget - but would prefer to use this one directly if I could.

**Comment by Seventhxiv** [comment]
Would also appreciate this update

**Comment by Koenari** [comment]
See #17. We are working on it, will be done soon

**Comment by Cyeniia** [comment]
Is there anything new on this topic? #17 has been merged.

**Comment by codemonkey85** [comment]
I too could really use an update on the NuGet.

**Comment by Koenari** [comment]
I have good news. "Soon" is now. Sorry for the delay, there were some organizational tasks to be done that held this up until now
