### ISSUE TITLE
Parsing Free Companies is broken for FCs with open Lodestone recruitment

### ISSUE THREAD

**Issue by Tawmy** [xivapi/NetStone#19]
Hey there,

in addition to opening recruitment for a free company in-game, it's also possible to open recruitment on the Lodestone:

https://eu.finalfantasyxiv.com/lodestone/community_finder/

When a free company has opened recruitment, a banner is added to its Lodestone profile:

![Screenshot 2024-05-19 at 13 00 01](https://github.com/xivapi/NetStone/assets/22292560/cdbb2ab9-cb2b-4103-963a-d1c2cf1167c2)

This banner seems to be breaking the free company parser, particularly when parsing reputation. I've had reputations assigned to the wrong grand company, and one of them failing to parse at all as a result. I don't feel familiarised enough with the parser's workings to fix this myself, so I'd appreciate if someone more accustomed to it were to take a look at this issue.

**Comment by Koenari** [comment]
Should be fixed by https://github.com/xivapi/lodestone-css-selectors/pull/26 without an update here
