### ISSUE TITLE
Allow Definitions to be provided when creating a Client

### ISSUE THREAD

**Issue by Granock** [xivapi/NetStone#23]
Hi, I love the lib, and am currently starting my first project using it. 

For that project and maybe other projects like it, there is a small improvement the lib could have.
Currently, when creating a client, the definitions are always downloaded via a HttpClient. 
In my use case I am running the parser in a serverless-function that can be started and stopped dynamically. 

To optimize startup-times, i’d like to be able to provide the definitions when creating the LodestoneClient.
This would allow me just store the definitions-data in a shared storage and update that version periodically, instead
of always downloading it.

if this isn't wanted i can understand, just wanted to ask.

**Comment by Koenari** [comment]
Done 841d81ad627ed3b5bcef2878fd691fa2439a1067
