### ISSUE TITLE
IndexOutOfRange Exception on ClassJobEntry.ParseExp

### ISSUE THREAD

**Issue by twobe7** [xivapi/NetStone#6]
LodestoneParseable.Parse returns either the inner text if no regex string or the second result of the parsed regex.

ClassJobEntry uses above method to parse ExpString. When it calls its own ParseExp method, an IndexOutOfRange exception occurs due to the line
`this.expMaxVal = long.Parse(expVals[1]);`

Currently the CheckCharacterFull test is failing due to fetching the Warrior job where the exp string should be "0 / 5,992,000" but is only parsing as "0".

**Comment by twobe7** [comment]
LodestoneParseable.Parse - Result of `res` for Warrior ExpString
```
res
Count = 3
    [0]: {0 / 5,992,000}
    [1]: {0}
    [2]: {5,992,000}
```

Method should be returning `res[0].Value`

Making this change results in a failed test for `CheckFreeCompany` as parsing on field Formed as this requires the second result in order to parse correctly.

Potential solution to add param for index on result allowing default to apply 
```
protected string Parse(DefinitionsPack pack, int regexResultIndex = 1)
{
    if (!string.IsNullOrEmpty(pack.Regex))
    {
        var res = ParseRegex(pack);

        if (res == null)
            return null;

        if (res.Count != 0)
            return res.ElementAtOrDefault(regexResultIndex)?.Value ?? ParseInnerText(pack);
    }

    return ParseInnerText(pack);
}
```

Allows ParseTime (used by FreeCompany.Formed) to take first option while all else takes second option.

**Comment by Koenari** [comment]
Experience parsing is working again since c259628575bc638fcf22de4a3e1813f3e0570c0b
