### ISSUE TITLE
Dictionary cant be created using CharacterClassJob.ClassJobDict

### ISSUE THREAD

**Issue by RealFriesi** [xivapi/NetStone#7]
This line here:
https://github.com/xivapi/NetStone/blob/52e27039d5c3ae2d12a8e98279cd67a80411ff09/NetStone/Model/Parseables/Character/ClassJob/CharacterClassJob.cs#L210
should contain `{StaticData.ClassJob.Gladiator, Paladin}`

System.ArgumentException: An item with the same key has already been added. Key: Pugilist

**Comment by Koenari** [comment]
Fixed in #10
